# Generated by Django 4.0 on 2021-12-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='family',
            new_name='family_id',
        ),
    ]
